### ISSUE TITLE
Casual difficulty option not showing up in sourcemod menu.

### ISSUE THREAD

**Issue by Addasu** [zeThijs/SM-NMRiH-diffmoder_fork#3]
This could be a problem on my end. Not 100%. But I thought I would share anyways.
![Screenshot 2023-06-30 164723](https://github.com/zeThijs/SM-NMRiH-diffmoder_fork/assets/66442120/40926769-f0e8-4ad9-b44f-b4c3b1fea492)

**Comment by zeThijs** [comment]
Ah this was a bug in a previous version, but i think i forgot to release the new version, hold up

**Comment by zeThijs** [comment]
Added latest version compilation in the latest update, feel free to grab that

**Comment by Addasu** [comment]
Great stuff. Thanks for the update!
