### ISSUE TITLE
Request for official mutators to be implemented into the plugin.

### ISSUE THREAD

**Issue by Addasu** [zeThijs/SM-NMRiH-diffmoder_fork#4]
Not sure if this is even possible, but it would be pretty neat to have.

**Comment by zeThijs** [comment]
I'm not super familiar with the official mutators, can you describe them for me? :)

**Comment by Addasu** [comment]
Honestly, I don't even know myself. It was a request from some players on my servers. I'll have to do some research myself and get back to you on this.

**Comment by zeThijs** [comment]
I implemented a mutator toggle as an unreleased feature at some point, might be able to add it fully

**Comment by zeThijs** [comment]
Should i adminwall mutatoroptions?

**Comment by Addasu** [comment]
> 

I would say no. As long as there are options to reset everything on map change, it should be fine in player hands.

**Comment by zeThijs** [comment]
I had been holding off adding this feature as i cannot guarantee the mutators wont break if hold loading / unloading..
Figured I'd add without support for the bugs loading mutators might bring xd It's up to server admins to either fix or dont use buggy mutators.
