### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Sanj1Ng** [zeThijs/SM-NMRiH-diffmoder_fork#5]
Is there a solution?

**Comment by zeThijs** [comment]
Can you provide an error log?

**Comment by zeThijs** [comment]
Alternatively you may grab the latest compile in latest release :)

**Comment by Sanj1Ng** [comment]
> 或者你可以抓住的最新汇编的最新版本：)

Thanks, I downloaded the latest plugin and it compiles

**Comment by zeThijs** [comment]
Good to hear!

**Comment by Sanj1Ng** [comment]
Can not run on the server, cfg file can not load

**Comment by zeThijs** [comment]
Did you add the gamedata and translation files as well?
