### ISSUE TITLE
[problem]Plugin cannot run

### ISSUE THREAD

**Issue by Sanj1Ng** [zeThijs/SM-NMRiH-diffmoder_fork#7]
I updated the latest version of the plugin on my server，But it doesn't work and can't even load the cfg file?

**Comment by Sanj1Ng** [comment]
Do you need to restart the server?

**Comment by zeThijs** [comment]
Did you add the gamedata and translation files as well?

**Comment by Sanj1Ng** [comment]
yes, I overwrote all the folders，I'll try again later to see if it's my fault.

**Comment by Sanj1Ng** [comment]
Strangely, I did not experience such problems with the previous version of the plugin    :>

**Comment by zeThijs** [comment]
I might have overlooked something, it's been a while since i looked at this. Looking into it

**Comment by zeThijs** [comment]
Do you get any errors in console?

**Comment by Sanj1Ng** [comment]
Okay, it's my problem.  I rewrote the folder and it worked.  Excuse me

**Comment by zeThijs** [comment]
Nps, enjoy the plugin!
